/* Churn retention dashboard — data from data.js (window.DASH), generated by churn_insurance_master.ipynb (Section 24.5).
   Plain SVG charts (no external libraries) → works offline and on any static host (Vercel). */
(function () {
  "use strict";
  const D = window.DASH || {};
  const $ = (id) => document.getElementById(id);
  const NS = "http://www.w3.org/2000/svg";
  const css = (v) => getComputedStyle(document.documentElement).getPropertyValue(v).trim();
  const fmtPct = (v, d = 1) => (v == null || isNaN(v) ? "–" : (100 * v).toFixed(d) + "%");
  const fmtNum = (v, d = 1) => {
    if (v == null || isNaN(v)) return "–";
    const a = Math.abs(v);
    if (a >= 1e9) return (v / 1e9).toFixed(d) + "B";
    if (a >= 1e6) return (v / 1e6).toFixed(d) + "M";
    if (a >= 1e3) return (v / 1e3).toFixed(d) + "K";
    return v.toFixed(a < 10 ? 2 : 0);
  };

  /* ---------- theme ---------- */
  const themeBtn = $("themeBtn");
  try { const t = localStorage.getItem("dash-theme"); if (t) document.documentElement.dataset.theme = t; } catch (e) {}
  themeBtn.addEventListener("click", () => {
    const dark = document.documentElement.dataset.theme === "dark" ||
      (!document.documentElement.dataset.theme && matchMedia("(prefers-color-scheme: dark)").matches);
    document.documentElement.dataset.theme = dark ? "light" : "dark";
    try { localStorage.setItem("dash-theme", document.documentElement.dataset.theme); } catch (e) {}
    renderAll();
  });

  /* ---------- tooltip ---------- */
  const tip = $("tip");
  function showTip(evt, rows) {
    tip.replaceChildren();
    rows.forEach(([k, v], i) => {
      const line = document.createElement("div");
      if (i === 0) { const s = document.createElement("strong"); s.textContent = v; line.append(s, document.createTextNode(" " + k)); }
      else { const a = document.createElement("span"); a.className = "k"; a.textContent = k + ": "; line.append(a, document.createTextNode(v)); }
      tip.append(line);
    });
    tip.hidden = false;
    const x = Math.min(evt.clientX + 14, innerWidth - tip.offsetWidth - 8);
    const y = Math.min(evt.clientY + 14, innerHeight - tip.offsetHeight - 8);
    tip.style.left = x + "px"; tip.style.top = y + "px";
  }
  const hideTip = () => { tip.hidden = true; };

  /* ---------- svg helpers ---------- */
  function el(tag, attrs, parent) {
    const e = document.createElementNS(NS, tag);
    for (const k in attrs) e.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(e);
    return e;
  }
  function text(parent, x, y, s, cls, anchor) {
    const t = el("text", { x, y, "text-anchor": anchor || "start" }, parent);
    if (cls) t.setAttribute("class", cls);
    t.textContent = s;
    return t;
  }
  const cw = (container, def) => Math.max(300, Math.min(1100, container.clientWidth || def || 640));
  function svgBox(container, w, h) {
    container.replaceChildren();
    return el("svg", { viewBox: `0 0 ${w} ${h}`, role: "img" }, container);
  }
  function hover(node, rows) {
    node.style.cursor = "default";
    node.addEventListener("pointermove", (e) => showTip(e, rows));
    node.addEventListener("pointerleave", hideTip);
    node.setAttribute("tabindex", "0");
    node.addEventListener("focus", (e) => { const r = node.getBoundingClientRect(); showTip({ clientX: r.right, clientY: r.top }, rows); });
    node.addEventListener("blur", hideTip);
  }
  function empty(container, msg) { container.replaceChildren(); const p = document.createElement("p"); p.className = "empty"; p.textContent = msg; container.append(p); }

  /* ---------- table ---------- */
  function table(container, t, numericCols) {
    if (!t || !t.rows || !t.rows.length) return empty(container, "No data for this section.");
    const tb = document.createElement("table");
    const thead = tb.createTHead().insertRow();
    t.columns.forEach((c, i) => { const th = document.createElement("th"); th.textContent = c; if (isNum(t.rows, i)) th.className = "num"; thead.append(th); });
    const body = tb.createTBody();
    t.rows.forEach((r) => {
      const tr = body.insertRow();
      r.forEach((v, i) => { const td = tr.insertCell(); td.textContent = v == null ? "" : String(v); if (isNum(t.rows, i)) td.className = "num"; });
    });
    container.replaceChildren(tb);
    return tb;
  }
  function isNum(rows, i) { return rows.slice(0, 20).every((r) => r[i] === null || r[i] === "" || /^[-+]?[\d.,]+[%×xKMB]?$/.test(String(r[i]))); }

  /* ---------- charts ---------- */
  function hbar(container, items, opt) {
    // items: [{label, value, lo?, hi?, fill?, tip: [[k,v]...]}]
    if (!items || !items.length) return empty(container, "No data.");
    const W = cw(container), rowH = 26, L = Math.min(W * 0.38, 250, 40 + 6.2 * Math.max(...items.map((d) => d.label.length))), R = 60, T = 6;
    const H = T + rowH * items.length + 26;
    const svg = svgBox(container, W, H);
    const max = opt.max != null ? opt.max : Math.max(...items.map((d) => (d.hi != null ? d.hi : d.value))) * 1.08;
    const x = (v) => L + (W - L - R) * (v / max);
    for (let g = 0; g <= 4; g++) {
      const v = (max * g) / 4, gx = x(v);
      el("line", { x1: gx, x2: gx, y1: T, y2: H - 22, class: "gridline" }, svg);
      text(svg, gx, H - 6, opt.fmt(v), null, "middle");
    }
    if (opt.ref != null) el("line", { x1: x(opt.ref), x2: x(opt.ref), y1: T, y2: H - 22, stroke: css("--critical"), "stroke-dasharray": "4 3", "stroke-width": 1.5 }, svg);
    items.forEach((d, i) => {
      const y = T + i * rowH;
      const maxc = Math.max(8, Math.floor((L - 10) / 6.2));
      text(svg, L - 8, y + rowH / 2 + 4, d.label.length > maxc ? d.label.slice(0, maxc - 1) + "…" : d.label, "lbl", "end");
      const bw = Math.max(1, x(d.value) - L);
      const bar = el("rect", { x: L, y: y + 6, width: bw, height: rowH - 12, rx: 3, fill: d.fill || css("--s1") }, svg);
      if (d.hollow) { bar.setAttribute("fill", "none"); bar.setAttribute("stroke", d.fill || css("--s1")); bar.setAttribute("stroke-width", 1.5); }
      if (d.lo != null && d.hi != null) {
        el("line", { x1: x(d.lo), x2: x(d.hi), y1: y + rowH / 2, y2: y + rowH / 2, stroke: css("--ink2"), "stroke-width": 1.2 }, svg);
      }
      text(svg, x(d.hi != null ? d.hi : d.value) + 6, y + rowH / 2 + 4, opt.fmt(d.value), "val");
      const hit = el("rect", { x: 0, y, width: W, height: rowH, fill: "transparent" }, svg);
      hover(hit, d.tip || [[d.label, opt.fmt(d.value)]]);
    });
  }

  function lines(container, series, opt) {
    // series: [{name, color, points:[[x,y]], dash}]
    series = (series || []).filter((s) => s.points && s.points.length);
    if (!series.length) return empty(container, "No data.");
    const W = cw(container), H = Math.round(Math.min(320, Math.max(220, W * 0.55))), L = 52, R = 14, T = 10, B = 34;
    const svg = svgBox(container, W, H);
    const xs = series.flatMap((s) => s.points.map((p) => p[0])), ys = series.flatMap((s) => s.points.map((p) => p[1]));
    const xmax = opt.xmax != null ? opt.xmax : Math.max(...xs), xmin = opt.xmin != null ? opt.xmin : Math.min(0, ...xs);
    const ymin = opt.ymin != null ? opt.ymin : Math.min(...ys), ymax = opt.ymax != null ? opt.ymax : Math.max(...ys);
    const x = (v) => L + ((W - L - R) * (v - xmin)) / (xmax - xmin || 1);
    const y = (v) => T + ((H - T - B) * (ymax - v)) / (ymax - ymin || 1);
    for (let g = 0; g <= 4; g++) {
      const v = ymin + ((ymax - ymin) * g) / 4;
      el("line", { x1: L, x2: W - R, y1: y(v), y2: y(v), class: "gridline" }, svg);
      text(svg, L - 6, y(v) + 4, opt.fy(v), null, "end");
      const xv = xmin + ((xmax - xmin) * g) / 4;
      text(svg, x(xv), H - B + 16, opt.fx(xv), null, "middle");
    }
    el("line", { x1: L, x2: W - R, y1: H - B, y2: H - B, class: "axisline" }, svg);
    if (opt.xlab) text(svg, (L + W - R) / 2, H - 2, opt.xlab, null, "middle");
    series.forEach((s) => {
      const d = s.points.map((p, i) => (i ? "L" : "M") + x(p[0]).toFixed(1) + " " + y(p[1]).toFixed(1)).join(" ");
      el("path", { d, fill: "none", stroke: s.color, "stroke-width": 2, "stroke-dasharray": s.dash ? "5 4" : "none", "stroke-linejoin": "round" }, svg);
    });
    if (opt.marker) {
      el("circle", { cx: x(opt.marker[0]), cy: y(opt.marker[1]), r: 5, fill: css("--s2"), stroke: css("--surface"), "stroke-width": 2 }, svg);
    }
    const cross = el("line", { y1: T, y2: H - B, stroke: css("--axis"), "stroke-width": 1, visibility: "hidden" }, svg);
    const hit = el("rect", { x: L, y: T, width: W - L - R, height: H - T - B, fill: "transparent" }, svg);
    hit.addEventListener("pointermove", (e) => {
      const r = svg.getBoundingClientRect();
      const xv = xmin + ((e.clientX - r.left) / r.width * W - L) / (W - L - R) * (xmax - xmin);
      cross.setAttribute("x1", x(xv)); cross.setAttribute("x2", x(xv)); cross.setAttribute("visibility", "visible");
      const rows = [[opt.xlab || "", opt.fx(xv)]];
      series.forEach((s) => {
        let best = s.points[0];
        for (const p of s.points) if (Math.abs(p[0] - xv) < Math.abs(best[0] - xv)) best = p;
        rows.push([s.name, opt.fy(best[1])]);
      });
      rows[0] = [rows[0][0], rows[0][1]];
      showTip(e, [[opt.xlab || "", opt.fx(xv)], ...rows.slice(1)]);
    });
    hit.addEventListener("pointerleave", () => { cross.setAttribute("visibility", "hidden"); hideTip(); });
    const lg = document.createElement("div"); lg.className = "legend";
    if (series.length > 1) series.forEach((s) => { const sp = document.createElement("span"); const i = document.createElement("i"); if (s.dash) i.className = "dash"; i.style.setProperty("--c", s.color); sp.append(i, document.createTextNode(s.name)); lg.append(sp); });
    container.prepend(lg);
  }

  function vbars(container, items, opt) {
    if (!items || !items.length) return empty(container, "No data.");
    const W = cw(container), H = 280, L = 48, R = 10, T = 10, B = 54;
    const svg = svgBox(container, W, H);
    const max = Math.max(...items.map((d) => d.value)) * 1.12 || 1;
    const bw = (W - L - R) / items.length;
    const y = (v) => T + (H - T - B) * (1 - v / max);
    for (let g = 0; g <= 4; g++) { const v = (max * g) / 4; el("line", { x1: L, x2: W - R, y1: y(v), y2: y(v), class: "gridline" }, svg); text(svg, L - 6, y(v) + 4, opt.fmt(v), null, "end"); }
    items.forEach((d, i) => {
      const x0 = L + i * bw;
      el("rect", { x: x0 + bw * 0.18, y: y(d.value), width: bw * 0.64, height: H - B - y(d.value), rx: 3, fill: d.fill || css("--s1") }, svg);
      const t = text(svg, x0 + bw / 2, H - B + 14, d.label.length > 14 ? d.label.slice(0, 13) + "…" : d.label, "lbl", "middle");
      if (items.length > 6) t.setAttribute("transform", `rotate(-25 ${x0 + bw / 2} ${H - B + 14})`);
      const hit = el("rect", { x: x0, y: T, width: bw, height: H - T - B, fill: "transparent" }, svg);
      hover(hit, d.tip || [[d.label, opt.fmt(d.value)]]);
    });
    el("line", { x1: L, x2: W - R, y1: H - B, y2: H - B, class: "axisline" }, svg);
  }

  function dotCI(container, items, opt) {
    if (!items || !items.length) return empty(container, "No data.");
    const W = cw(container), rowH = 30, L = Math.min(W * 0.42, 260, 40 + 6 * Math.max(...items.map((d) => d.label.length))), R = 20, T = 8;
    const H = T + rowH * items.length + 26;
    const svg = svgBox(container, W, H);
    const lo = Math.min(...items.map((d) => Math.min(d.lo, d.value, d.alt != null ? d.alt : d.value, opt.ref != null ? opt.ref : d.lo)));
    const hi = Math.max(...items.map((d) => Math.max(d.hi, d.value, d.alt != null ? d.alt : d.value, opt.ref != null ? opt.ref : d.hi)));
    const pad = (hi - lo) * 0.08 || 0.01;
    const x = (v) => L + (W - L - R) * (v - (lo - pad)) / (hi - lo + 2 * pad);
    for (let g = 0; g <= 4; g++) { const v = lo - pad + ((hi - lo + 2 * pad) * g) / 4; el("line", { x1: x(v), x2: x(v), y1: T, y2: H - 22, class: "gridline" }, svg); text(svg, x(v), H - 6, opt.fmt(v), null, "middle"); }
    if (opt.ref != null) el("line", { x1: x(opt.ref), x2: x(opt.ref), y1: T, y2: H - 22, class: "axisline", "stroke-width": 1.5 }, svg);
    items.forEach((d, i) => {
      const yy = T + i * rowH + rowH / 2;
      const maxc = Math.max(8, Math.floor((L - 12) / 6));
      text(svg, L - 10, yy + 4, d.label.length > maxc ? d.label.slice(0, maxc - 1) + "…" : d.label, "lbl", "end");
      el("line", { x1: x(d.lo), x2: x(d.hi), y1: yy, y2: yy, stroke: css("--ink2"), "stroke-width": 1.5 }, svg);
      if (d.alt != null) el("path", { d: `M${x(d.alt) - 4} ${yy - 4} L${x(d.alt) + 4} ${yy + 4} M${x(d.alt) - 4} ${yy + 4} L${x(d.alt) + 4} ${yy - 4}`, stroke: css("--s2"), "stroke-width": 2 }, svg);
      el("circle", { cx: x(d.value), cy: yy, r: 5, fill: d.fill || css("--s1"), stroke: css("--surface"), "stroke-width": 2 }, svg);
      const hit = el("rect", { x: 0, y: yy - rowH / 2, width: W, height: rowH, fill: "transparent" }, svg);
      hover(hit, d.tip);
    });
  }

  /* ---------- sections ---------- */
  const tabsDef = [["overview", "Overview"], ["drivers", "Drivers"], ["timing", "Timing"], ["model", "Model"], ["campaign", "Campaign & causal"], ["actions", "Actions"], ["method", "Methodology"]];
  function setupTabs() {
    const nav = $("tabs");
    tabsDef.forEach(([id, lab], i) => {
      const b = document.createElement("button");
      b.type = "button"; b.textContent = lab; b.setAttribute("role", "tab"); b.dataset.id = id;
      b.addEventListener("click", () => select(id));
      nav.append(b);
    });
    const start = (location.hash || "#overview").slice(1);
    select(tabsDef.some((t) => t[0] === start) ? start : "overview");
  }
  function select(id) {
    document.querySelectorAll(".panel").forEach((p) => p.classList.toggle("active", p.id === id));
    document.querySelectorAll(".tabs button").forEach((b) => b.setAttribute("aria-selected", b.dataset.id === id ? "true" : "false"));
    if (location.hash.slice(1) !== id) history.replaceState(null, "", "#" + id);
    renderAll();
  }

  function renderHeader() {
    const m = D.meta || {};
    $("eyebrow").textContent = [m.team ? "Team " + m.team : "", m.company || ""].filter(Boolean).join(" · ");
    $("title").textContent = m.title || "Customer Churn & Retention";
    document.title = m.short_title || "Churn Retention Dashboard";
    $("subtitle").textContent = `${(m.n || 0).toLocaleString()} customers · churn rate ${fmtPct(m.churn_rate)} · final model ROC-AUC ${m.auc ? m.auc.toFixed(3) : "–"}`;
    $("foot").textContent = `Team ${m.team || ""}${m.members && m.members.length ? " (" + m.members.join(", ") + ")" : ""} · generated ${m.generated || ""} by churn_insurance_master.ipynb · all metrics out-of-fold · ${m.currency || ""} values`;
  }
  function renderKpis(container, kpis) {
    container.replaceChildren();
    (kpis || []).forEach((k) => {
      const d = document.createElement("div"); d.className = "kpi";
      const a = document.createElement("div"); a.className = "lab"; a.textContent = k.label;
      const b = document.createElement("div"); b.className = "val"; b.textContent = k.value;
      const c = document.createElement("div"); c.className = "det"; c.textContent = k.detail || "";
      d.append(a, b, c); container.append(d);
    });
  }
  function renderOverview() {
    const m = D.meta || {};
    if (m.context || (m.questions && m.questions.length)) {
      $("contextCard").hidden = false;
      $("caseContext").textContent = m.context || "";
      const ql = $("caseQuestions"); ql.replaceChildren();
      (m.questions || []).forEach((q) => { const li = document.createElement("li"); li.textContent = q; ql.append(li); });
    }
    renderKpis($("kpis"), D.kpis);
    const ol = $("findings"); ol.replaceChildren();
    (D.findings || []).forEach((f) => { const li = document.createElement("li"); li.textContent = f; ol.append(li); });
    hbar($("driverShare"), (D.driver_share || []).map((d) => ({
      label: d.name, value: d.share, hollow: !d.actionable, fill: css("--s1"),
      tip: [[d.name, d.share.toFixed(1) + "%"], ["Actionable", d.actionable ? "yes" : "no"]],
    })), { fmt: (v) => v.toFixed(0) + "%" });
  }
  function renderDrivers() {
    const sel = $("driverSel");
    if (!sel.options.length) {
      (D.drivers || []).forEach((d, i) => { const o = document.createElement("option"); o.value = i; o.textContent = d.name; sel.append(o); });
      sel.addEventListener("change", renderDrivers);
    }
    const d = (D.drivers || [])[+sel.value || 0];
    if (!d) empty($("driverChart"), "No driver data.");
    else hbar($("driverChart"), d.levels.map((l) => ({
      label: String(l.level), value: l.rate, lo: l.lo, hi: l.hi, fill: l.rate > D.meta.churn_rate ? css("--s2") : css("--s1"),
      tip: [[String(l.level), fmtPct(l.rate)], ["95% CI", fmtPct(l.lo) + " – " + fmtPct(l.hi)], ["Customers", l.n.toLocaleString()], ["Lift", (l.rate / D.meta.churn_rate).toFixed(2) + "×"]],
    })), { fmt: (v) => fmtPct(v, 0), ref: D.meta.churn_rate });
    table($("evidenceTable"), D.evidence);
    table($("segTable"), D.segments);
  }
  function renderTiming() {
    const km = D.km || {};
    const colors = { High: css("--s2"), Medium: css("--s4"), Low: css("--s1"), All: css("--ink2") };
    lines($("kmChart"), (km.series || []).map((s) => ({ name: s.name, color: colors[s.name] || css("--s3"), points: s.points, dash: s.name === "All" })),
      { fx: (v) => v.toFixed(0), fy: (v) => fmtPct(v, 0), xlab: "Tenure (" + (km.unit || "") + ")" });
    vbars($("hazardChart"), (D.hazard || []).map((h) => ({ label: h.interval, value: h.hazard, fill: css("--s2"),
      tip: [[h.interval, fmtPct(h.hazard, 2)], ["Per", D.hazard_label || "period"], ["Events", (h.events || 0).toLocaleString()]] })), { fmt: (v) => fmtPct(v, 1) });
  }
  function renderModel() {
    const g = D.gains || [];
    lines($("gainsChart"), [{ name: "Model", color: css("--s1"), points: g.map((p) => [p.x, p.y]) },
      { name: "Random", color: css("--muted"), points: [[0, 0], [100, 100]], dash: true }],
      { fx: (v) => v.toFixed(0) + "%", fy: (v) => v.toFixed(0) + "%", xlab: "% of customers contacted", ymin: 0, ymax: 100, xmin: 0, xmax: 100 });
    dotCI($("modelChart"), (D.models || []).map((m) => ({ label: m.model, value: m.auc, lo: m.lo, hi: m.hi, fill: m.final ? css("--s2") : css("--s1"),
      tip: [[m.model, m.auc.toFixed(4)], ["95% CI", m.lo.toFixed(3) + " – " + m.hi.toFixed(3)], ["PR-AUC", (m.pr_auc || 0).toFixed(3)]] })), { fmt: (v) => v.toFixed(3) });
    table($("modelTable"), D.model_table);
  }
  function renderCampaign() {
    const c = D.campaign;
    if (!c || !c.pct || !c.pct.length) { empty($("campChart"), "No campaign data (no value column)."); return; }
    const sS = $("sSucc"), sC = $("sCost");
    if (!sS.dataset.init) {
      sS.value = c.success; sC.max = Math.max(1, c.cost * 4); sC.step = Math.max(c.cost / 50, 0.01); sC.value = c.cost;
      [sS, sC].forEach((s) => s.addEventListener("input", renderCampaign)); sS.dataset.init = "1";
    }
    const succ = +sS.value, cost = +sC.value;
    $("oSucc").textContent = (succ * 100).toFixed(0) + "%"; $("oCost").textContent = fmtNum(cost) + " " + (c.unit || "");
    const prof = c.pct.map((p, i) => [p, succ * c.value[i] - cost * c.n[i]]);
    const rnd = c.pct.map((p, i) => [p, succ * c.value_random[i] - cost * c.n[i]]);
    let best = prof[0]; prof.forEach((p) => { if (p[1] > best[1]) best = p; });
    const bi = prof.indexOf(best);
    renderKpis($("campKpis"), [
      { label: "Best campaign size", value: best[0].toFixed(0) + "%", detail: (c.n[bi] || 0).toLocaleString() + " customers" },
      { label: "Max net benefit", value: fmtNum(best[1]) + " " + (c.unit || ""), detail: "vs " + fmtNum(rnd[bi][1]) + " random" },
      { label: "ROI", value: (cost * c.n[bi] > 0 ? (best[1] / (cost * c.n[bi])).toFixed(1) + "×" : "–"), detail: "net benefit ÷ cost" },
    ]);
    lines($("campChart"), [{ name: "Model (expected loss)", color: css("--s1"), points: prof }, { name: "Random", color: css("--muted"), points: rnd, dash: true }],
      { fx: (v) => v.toFixed(0) + "%", fy: (v) => fmtNum(v), xlab: "% of customers contacted", marker: best });
    dotCI($("causalChart"), (D.causal || []).map((r) => ({ label: r.label, value: r.ate, lo: r.lo, hi: r.hi, alt: r.naive,
      fill: r.robust ? css("--s3") : css("--s1"),
      tip: [[r.label, r.ate.toFixed(2) + " pp"], ["95% CI", r.lo.toFixed(2) + " to " + r.hi.toFixed(2)], ["Naive difference (×)", r.naive.toFixed(2) + " pp"], ["Robustness", r.verdict || ""]] })),
      { fmt: (v) => v.toFixed(1) + " pp", ref: 0 });
  }
  let custRows = null;
  function renderActions() {
    table($("recTable"), D.recs);
    table($("personaTable"), D.personas);
    const ct = D.customers;
    if (!ct || !ct.rows) { empty($("custTable"), "No scored customers (no test file)."); return; }
    const q = ($("custSearch").value || "").toLowerCase();
    if (!custRows) { custRows = ct.rows; $("custSearch").addEventListener("input", renderActions); }
    const rows = q ? custRows.filter((r) => r.join(" ").toLowerCase().includes(q)) : custRows;
    $("custNote").textContent = `${rows.length.toLocaleString()} of ${ct.total ? ct.total.toLocaleString() : custRows.length} scored customers shown (sorted by churn probability). Full list: tables/test_customer_action_list.csv`;
    table($("custTable"), { columns: ct.columns, rows: rows.slice(0, 500) });
  }
  function renderMethod() {
    const g = $("gallery");
    if (g.dataset.done) return;
    (D.figures || []).forEach((f) => {
      const fig = document.createElement("figure");
      const img = document.createElement("img"); img.src = "figures/" + f.file; img.alt = f.caption; img.loading = "lazy";
      const cap = document.createElement("figcaption"); cap.textContent = f.caption;
      fig.append(img, cap); g.append(fig);
    });
    g.dataset.done = "1";
  }
  function renderAll() {
    renderHeader();
    const active = (document.querySelector(".panel.active") || {}).id;
    try {
      ({ overview: renderOverview, drivers: renderDrivers, timing: renderTiming, model: renderModel, campaign: renderCampaign, actions: renderActions, method: renderMethod }[active] || renderOverview)();
    } catch (e) { console.error(e); }
  }
  setupTabs();
  addEventListener("hashchange", () => { const id = location.hash.slice(1); if (tabsDef.some((t) => t[0] === id)) select(id); });
  let rz; addEventListener("resize", () => { clearTimeout(rz); rz = setTimeout(renderAll, 150); });
})();
